Added [R]eload and [S]FO commands; minor improvements

diff --git a/pkgrename b/pkgrename
--- a/pkgrename
+++ b/pkgrename
@@ -35,7 +35,7 @@ customize() {
 # Script starts below
 
 show_usage() {
-  echo "Usage: ${0##*/} [-hrs] [file/directory ...]" >&2
+  echo "Usage: ${0##*/} [-fhor] [file/directory ...]" >&2
 }
 
 show_help() {
@@ -48,8 +48,8 @@ show_help() {
   echo "  Options:"
   echo "    -f  Force prompt when file name matches pattern"
   echo "    -h  Display this help info"
+  echo "    -o  Default to online search"
   echo "    -r  Traverse directories recursively"
-  echo "    -s  Search the PS Store for hopefully better titles"
   exit
 }
 
@@ -62,7 +62,7 @@ while [[ $1 == "-"?* ]]; do
       f) force_prompt=true ;;
       h) show_help ;;
       r) find_option= ;;
-      s) search_ps_store=true ;;
+      o) search_ps_store=true ;;
       *) show_usage; exit 1 ;;
     esac
   done
@@ -78,15 +78,16 @@ cleanup() {
 
 trap '{ echo; cleanup; }' SIGINT
 
-# Prints a message and reads user input until input is valid
+# Prints a message and reads a keystroke until input is valid
 # $1: Message, $2: Allowed characters
-userinput_char() {
+read_userinput() {
   local char
-  while read -e -t 0.01; do :; done
-  while [[ $char != [$2] ]]; do
+  while read -e -t 0.01; do true; done # Clear buffer
+  while [[ ${char,,} != [$2] ]]; do
     read -p "$1 " -n 1 char
+    echo
   done
-  echo "$char"
+  userinput=${char,,}
 }
 
 # https://www.ntfs.com/exfat-filename-dentry.htm
@@ -95,21 +96,26 @@ convert_to_exfat_filename() {
 }
 
 # Optionally searches the PS Store for better titles (option -s)
-cusa_search() {
+online_search() {
   case $content_id in
     UP*) url="https://store.playstation.com/en-us/product/$content_id" ;;
     EP*) url="https://store.playstation.com/en-gb/product/$content_id" ;;
     JP*) url="https://store.playstation.com/ja-jp/product/$content_id" ;;
     *) return ;;
   esac
-  cusa_search_result=$(curl --silent "$url" \
+  online_search_result=$(curl --silent "$url" \
     | grep -Po -m1 '<title>\K[^<]*(?=</title>)')
+  if [[ $online_search_result == "" ]]; then
+    echo "PS Store title search failed." >&2
+  else
+    title=$online_search_result
+  fi
 }
 
 # Accepts a PKG file and renames it
 pkgrename() {
   local app_ver category content_id title title_id version releasegroup \
-    newfilename cusa_search_result
+    newfilename online_search_result
   echo "${1##*/}"
   while IFS= read -r line; do
     case "${line%%=*}" in
@@ -141,49 +147,50 @@ pkgrename() {
     *[^a-z]tcd[^a-z]*) releasegroup="TCD" ;;
     *[^a-z]unlimited[^a-z]*) releasegroup="UNLiMiTED" ;;
   esac
-  # Optionally search the PS Store for hopefully better titles
-  if [[ $search_ps_store == true ]]; then
-    cusa_search
-    if [[ $cusa_search_result == "" ]]; then
-      echo "PS Store title search failed." >&2
-    else
-      title=$cusa_search_result
-    fi
-  fi
+  [[ $search_ps_store == true ]] && online_search # Option -o
   customize
   case "$category" in
     ac) category="$category_dlc" ;;
     gd) category="$category_game" ;;
     gp) category="$category_patch" ;;
   esac
-  newfilename=$(convert_to_exfat_filename "$(eval echo $pattern)")
-  echo "$newfilename"
-  if [[ $newfilename == "${1##*/}" && $force_prompt != true ]]; then
-    echo "Nothing to do."
-  elif [[ $rename_all == true ]]; then
-    mv "$1" "$(dirname "$1")/$newfilename"
-  else
-    local char=$(userinput_char "Rename? [Y]es [N]o [A]ll [E]dit [Q]uit:" ynaeq)
-    echo
-    case "$char" in
-      y) mv "$1" "$(dirname "$1")/$newfilename" ;;
-      a) mv "$1" "$(dirname "$1")/$newfilename"; rename_all=true ;;
-      e) read -i "$newfilename" -e userfilename
-         newfilename=$(convert_to_exfat_filename "$userfilename")
-         if [[ $newfilename != "$userfilename" ]]; then
-           echo "exFAT conversion   : $newfilename"
-         fi
-         mv "$1" "$(dirname "$1")/$newfilename"
-         ;;
-      q) cleanup ;;
-    esac
-  fi
+  title_backup=$title # For [R]eload
+  while true; do
+    newfilename=$(convert_to_exfat_filename "$(eval echo $pattern)")
+    echo "$newfilename"
+    if [[ $newfilename == "${1##*/}" && $force_prompt != true ]]; then
+      echo "Nothing to do."
+      break
+    elif [[ $rename_all == true ]]; then
+      mv "$1" "$(dirname "$1")/$newfilename"
+      break
+    else
+      read_userinput "Rename? [Y]es [N]o [A]ll [E]dit [O]nline [R]eload [S]FO [Q]uit:" ynaeorsq
+      case "$userinput" in
+        y) mv "$1" "$(dirname "$1")/$newfilename"; break ;;
+        n) break ;;
+        a) mv "$1" "$(dirname "$1")/$newfilename"; rename_all=true; break ;;
+        e) read -i "$newfilename" -e userfilename
+           newfilename=$(convert_to_exfat_filename "$userfilename")
+           if [[ $newfilename != "$userfilename" ]]; then
+             echo "After exFAT conversion:"
+           fi
+           mv "$1" "$(dirname "$1")/$newfilename"
+           break
+           ;;
+        o) online_search ;;
+        r) title=$title_backup ;;
+        s) echo; sfo "$1"; echo; ;;
+        q) cleanup ;;
+      esac
+    fi
+  done
   echo
 }
 
 while [[ $1 != "" ]]; do
   if [[ -d "$1" ]]; then
-    while IFS= read -r -d $'\0' pkg <&3; do
+    while IFS= read -r -d $'\0' -u 3 pkg; do # File descriptor 3 because: nested reads
       pkgrename "$pkg"
     done 3< <(find "$1" $find_option -iname '*.pkg' -type f -print0 | sort -z)
   elif [[ -f "$1" && ${1,,} == *.pkg ]]; then
